name: Test with Cosmos Emulator (via Docker-Compose)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run Tests In Container
      run: docker compose -f ./.devcontainer/docker-compose.yml run app --entrypoint /workspace "npm ci && npm run build && npm test"

